export const PermissionFlagsBits = Object.fromEntries(
  Object.entries({
    Administrator: 3,
    KickMembers: 1,
    BanMembers: 2,
    ManageChannels: 4,
    ManageGuild: 5,
    ViewAuditLog: 7,
    ViewChannel: 10,
    SendMessages: 11,
    ManageMessages: 13,
    EmbedLinks: 14,
    AttachFiles: 15,
    ReadMessageHistory: 16,
    MentionEveryone: 17,
    Connect: 20,
    Speak: 21,
    MuteMembers: 22,
    DeafenMembers: 23,
    MoveMembers: 24,
    ManageRoles: 28,
    ManageWebhooks: 29,
    ManageGuildExpressions: 30,
    CreatePublicThreads: 35,
    CreatePrivateThreads: 36,
    SendMessagesInThreads: 38,
    ModerateMembers: 40,
  }).map(([k, v]) => [k, 1n << BigInt(v)]),
);
