import test from'node:test';import assert from'node:assert/strict';import{statMatch,periodicGroup,detailBody,install}from'../src/modules/statDetails.mjs';import{rankingReferenceSVG,statSummarySVG,statPNG}from'../src/core/stat-reference-cards.mjs';import{avatarURLAllowed}from'../src/core/stat-avatar.mjs';
test('stat match never includes channels outside current audience',()=>assert.deepEqual(statMatch('g',['visible'],0,'u'),{guildId:'g',channelId:{$in:['visible']},userId:'u'}));
test('Istanbul daily threshold is calendar based',()=>{const g=periodicGroup(Date.parse('2026-09-08T22:30:00Z'));assert.equal(g.daily_messages.$sum.$cond[0].$gte[1],'2026-09-09');assert.equal(g.weekly_voice.$sum.$cond[0].$gte[1],'2026-09-03');});
test('detail empty state and four activity types',()=>{const s=detailBody('u',7,{}, {},'');assert.ok(s.includes('Veri bulunamadı.'));assert.ok(s.includes('Yayın Kanalları'));assert.ok(s.includes('Kamera Kanalları'));});
test('ranking escapes names and cannot embed arbitrary avatar URLs',()=>{const s=rankingReferenceSVG({rows:[{name:'<script>',avatar:'https://evil.test/x',value:'123'}]});assert.ok(!s.includes('<script>'));assert.ok(!s.includes('https://evil'));});
test('weekly camera field uses weekly rather than total count',()=>{const s=statSummarySVG({total:{camera:999000},week:{camera:60000}});assert.ok(s.includes('0 saat 1 dakika 0 saniye'));assert.ok(!s.includes('0 saat 16 dakika 39 saniye'));});
test('statistics image renderer produces PNG',async()=>{const b=await statPNG(rankingReferenceSVG());assert.equal(b.subarray(1,4).toString(),'PNG');});
for(const u of ['http://cdn.discordapp.com/avatars/a/b','https://cdn.discordapp.com.evil/avatars/a/b','https://u:p@cdn.discordapp.com/avatars/a/b','file:///etc/passwd','https://cdn.discordapp.com/attachments/a/b'])test('statistics avatar rejects '+u,()=>assert.equal(avatarURLAllowed(u),false));
test('stat query filters inaccessible channels in every aggregation',async()=>{const queries=[],commands=new Map(),target={id:'u',displayName:'Üye',joinedTimestamp:Date.now(),user:{displayAvatarURL:()=>''}},member={id:'viewer'};const channels=new Map([['public',{id:'public',permissionsFor:()=>({has:()=>true}),parentId:null}],['private',{id:'private',permissionsFor:()=>({has:()=>false})}]]);const ctx={c:{guildId:'g'},db:{collection:()=>({aggregate:pipe=>{queries.push(pipe);return{toArray:async()=>[]};}})},replace:(names,fn)=>names.forEach(n=>commands.set(n,fn)),add:(names,fn)=>names.forEach(n=>commands.set(n,fn)),onInteraction(){}};await install(ctx);let payload;await commands.get('stat')({guildId:'g',author:{id:'u'},guild:{members:{fetch:async id=>id==='u'?target:member},channels:{fetch:async()=>channels}},reply:async p=>payload=p},[]);assert.equal(queries.length,6);for(const pipe of queries)assert.deepEqual(pipe[0].$match.channelId,{$in:['public']});assert.ok(payload.files[0].attachment.length>0);});
